# Generated by Django 3.2.4 on 2021-06-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210625_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='user',
        ),
        migrations.CreateModel(
            name='UserInterviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
